[package]
name = "option-symbology"
version = "0.1.0"
authors = ["Tobias Breitwieser <tobias@breitwieser.biz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
fancy-regex = "0.5"